spring:
    datasource:
        url: jdbc:mysql://localhost:3306/showplaform?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            min-idle: 5
            max-active: 20
            initial-size: 5
            max-wait: 6000
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            filters: stat,wall
    servlet:
        multipart:
            max-request-size: 1000GB  # 上传文件总的最大值 默认10MB
            max-file-size: 1000GB #单个文件最大值 默认10MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
    port: 8081


